# Generated by Django 4.2.13 on 2024-07-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_dates_remove_job_review_job_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
